language: node_js
branches:
  only:
    - master
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
script:
  - npm run-script lint
  - npm run-script flow
  - npm run-script test
  - npm run-script cover
